'use client';
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar/Navbar";
import { ReactNode } from 'react';
import { base } from 'viem/chains';
import { OnchainKitProvider } from '@coinbase/onchainkit';
import { WagmiProvider } from 'wagmi';
import { wagmiConfig } from 'wagmi';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
// type Props = { children: ReactNode };
const inter = Inter({ subsets: ["latin"] });

 const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <WagmiProvider config={wagmiConfig}>
        <QueryClientProvider client={QueryClient}>
       <OnchainKitProvider apiKey="YOUR_PUBLIC_API_KEY" chain={base}>
      
      <body className={inter.mainbody}>
        <Navbar/>
        {children}</body>
    </OnchainKitProvider>
    </QueryClientProvider>
    </WagmiProvider>
    </html>
  );
}
